### ISSUE TITLE
Optimize exchange pattern search for nodes to filter on node arch

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/exchange-api#163]
The code should look at the services that a pattern directly references (don't need to do a deep search of all the required services), make a list of all the architectures, and when looking for nodes should filter out nodes whose architecture doesn't match.

- [x] The relevant route is `/orgs/:orgid/patterns/:pattern/search`, which is currently in NodesRoutes.scala for historical reasons, but should be moved to PatternsRoutes.scala
- [x] Look at `/orgs/:orgid/business/policies/:policy/search` as an example. Notice that the building of the  `nodeQuery` will have to be moved down into the db thread so that first the pattern can be queried. Also note that these special cases should be handled for the arch filtering:
  - [x] If the node arch isn't set (because it is an older node), the node should not be filtered out, i.e. it should be included in the returned list. (We didn't have to handle that case in the business policy search, because it was new like the node arch support.)
  - [x] Like the business policy search, handle the case in which one of the services in the pattern has arch set to `""` or `"*"`. We don't actually support that in patterns yet, but i think we will in the future.

**Comment by sf2ne** [comment]
Verified on major peacock:

Test 1: No nodes available
```
 curl -X POST -sS "https://9.30.210.34:8443/ec-exchange/v1/orgs/major-peacock-icp-cluster/patterns/pattern-ibm.helloworld/search" -H "Authorization:Basic <admin-auth>" -H "accept: application/json" -H "Content-Type: application/json" -d "@<path-to-file>/pattern_search_no_arch.json"

{"nodes":[],"lastIndex":0}
```

Test 2: Added three nodes, not searching on arch
```
curl -X POST -sS "https://9.30.210.34:8443/ec-exchange/v1/orgs/major-peacock-icp-cluster/patterns/pattern-ibm.helloworld/search" -H "Authorization:Basic <admin-auth>" -H "accept: application/json" -H "Content-Type: application/json" -d "@<path-to-file>/pattern_search_no_arch.json"

{"nodes":[{"id":"major-peacock-icp-cluster/sfaruk-testnodeid3","msgEndPoint":"","publicKey":"sadiyahpublickey3"},{"id":"major-peacock-icp-cluster/sfaruk-testnodeid2","msgEndPoint":"","publicKey":"sadiyahpublickey2"},{"id":"major-peacock-icp-cluster/sfaruk-testnodeid1","msgEndPoint":"","publicKey":"sadiyahpublickey1"}],"lastIndex":0}
```

Test 3: Searching on arch=amd64
```
curl -X POST -sS "https://9.30.210.34:8443/ec-exchange/v1/orgs/major-peacock-icp-cluster/patterns/pattern-ibm.helloworld/search" -H "Authorization:Basic <admin-auth>" -H "accept: application/json" -H "Content-Type: application/json" -d "@<path-to-file>/pattern_search_on_arch.json"

{"nodes":[{"id":"major-peacock-icp-cluster/sfaruk-testnodeid2","msgEndPoint":"","publicKey":"sadiyahpublickey2"},{"id":"major-peacock-icp-cluster/sfaruk-testnodeid1","msgEndPoint":"","publicKey":"sadiyahpublickey1"}],"lastIndex":0}
```

Test 4: Searching on arch=arm64
```
curl -X POST -sS "https://9.30.210.34:8443/ec-exchange/v1/orgs/major-peacock-icp-cluster/patterns/pattern-ibm.helloworld/search" -H "Authorization:Basic <admin-auth>" -H "accept: application/json" -H "Content-Type: application/json" -d "@<path-to-file>/pattern_search_on_arch.json"

{"nodes":[{"id":"major-peacock-icp-cluster/sfaruk-testnodeid3","msgEndPoint":"","publicKey":"sadiyahpublickey3"}],"lastIndex":0}
```
