### ISSUE TITLE
Add new GET /orgs/{orgid}/status API

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/exchange-api#174]
To provide org-specific status info, similar to the `/admin/status` API. So something like:
```
{
  "msg": "Exchange server operating normally",
  "numberOfUsers": 114,
  "numberOfNodes": 314,
  "numberOfRegisteredNodes": 302,
  "numberOfNodeAgreements": 61,
  "numberOfNodeMsgs": 0,
  "numberOfAgbots": 3,
  "numberOfAgbotAgreements": 468,
  "numberOfAgbotMsgs": 0,
  "dbSchemaVersion": 26,
}
```
(but only for the org that the user has authenticated for).

And if it isn't too hard, add the number of nodes that are registered, for both this and the `/admin/status` APIs

**Comment by sf2ne** [comment]
We'll need a new hzn command to access the new api route.

**Comment by bmpotter** [comment]
@megha070 For this issue, start by copying the `​GET /v1​/orgs​/{orgid}` API in `OrgsRoutes.scala`. Then for the DB access (inside db.run) you can use the code from the `GET /admin/status` API in `AdminRoutes.scala` as a starting point. The DB queries will be similar, except filtered for this specific org.

**Comment by bmpotter** [comment]
I verified this issue implementation on our staging cluster.
