### ISSUE TITLE
New exchange search API to return how many nodes a particular service is currently running on

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/exchange-api#181]
The UI needs to be able to get this quickly to show this to a user for any particular service, so implement a new api `POST /orgs/{id}/services/{id}/search`, which returns the number of nodes the service is currently running on.

The info needed for this new api is in the `nodes/{id}/status` resource. The problem is that it is buried in the `services` field (which is a string of json), so sql can't currently be used to quickly find the info in the db.

This is hard to handle efficiently, because the only way to enable sql searches is to have the data you want in fixed field (column) names. The only way i can think of to do this (but this feels like a hack) is to: add another field to the `status` resource called `runningServices` which is a string in the form:
```
|org1/serviceid1|org2/serviceid2|...
```

where serviceid is our combined service id `<svc-name>_<svc-version>_<service-arch>`.

On each `PUT nodes/{id}/status`, go thru the `services` field in the input body and build the value of the `runningServices` field.

Then to implement the `POST /orgs/{id}/services/{id}/search` api, you can form a db query with `like %|<org>/<serviceid>|%` and return the number you get back from the query

**Comment by sf2ne** [comment]
- Varatep would like the list of nodes running the service returned instead of just the count
- Maybe: include in the list (node Id and timestamp)

**Comment by sf2ne** [comment]
- [ ] put in skeleton of POST search route
- [ ] add `runningServices` field to `status` resource in `nodes`
- [ ] build value of `runningServices` on every PUT
- [ ] implement database query in POST search route

**Comment by sf2ne** [comment]
This issue is kind of out of date now, the new route is explained in: https://github.com/open-horizon/exchange-api/issues/224
