### ISSUE TITLE
Penetration test finding - Session token in URL 

### ISSUE THREAD

**Issue by ctiijima** [open-horizon/exchange-api#195]
The following is from the penetration test team:

**Description**
Sensitive information within URLs may be logged in various locations, including the user's browser, the webserver, and any forward or reverse proxy servers between the two endpoints. URLs may also be displayed on-screen, bookmarked or emailed around by users. They may be disclosed to third parties via the Referrer header when any off-site links are followed. Placing session tokens into the URL increases the risk that they will be captured by an attacker.
Note: Though the token in the URL is not mandatory to pass, it is always best practice that sensitive information shouldn't be passed in the URL.

**Affected URL/API(s)**
https://<host>:8443/ec-exchange/v1

**Request/Response**
Request:
POST /ec-exchange/v1/orgs/<host>/nodes/test-node/msgs?username=test- agbot1&password=test HTTP/1.1
Content-Type: application/json
User-Agent: PostmanRuntime/7.15.2
Accept: */*
Cache-Control: no-cache
Postman-Token: 58cd1db1-8d22-4c7f-8f89-fe1e8dbaa302
Host: <host>:8443
Accept-Encoding: gzip, deflate
Content-Length: 63
Connection: close
{
"message": "<script>alert(1)</script>", "ttl": 86400
}

Response:
HTTP/1.1 201 Created
Date: Wed, 31 Jul 2019 06:02:44 GMT
Content-Type: application/json;charset=utf-8
Connection: close
Access-Control-Allow-Credentials: true
Access-Control-Max-Age: 1800
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,HEAD,OPTIONS,PATCH X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Length: 42
{"code":"ok","msg":"node msg 41 inserted"}

**Risk Assessment**
Placing session tokens or credentials into the URL increases the risk that they will be captured by an attacker.

**Fix Recommendation**
Applications/service should use an alternative mechanism for transmitting session tokens, such as HTTP cookies or hidden fields in forms that are submitted using the POST method

**Comment by bmpotter** [comment]
Passwords and tokens are no longer supported in exchange 2.x
