### ISSUE TITLE
Penetration test finding - CORS Misconfiguration ?

### ISSUE THREAD

**Issue by ctiijima** [open-horizon/exchange-api#196]
Hold off on fixing this. Our move to akka-http might give us an easy way to fix this: https://github.com/lomigmegard/akka-http-cors

The following is from the penetration test team:

**Description**
Cross-Origin Resource Sharing (CORS) is a mechanism that allows web sites to request resources from external sites, avoiding the need to duplicate them. When granting access to external sites, they may also perform various actions on the granting site, as well as run scripts on them. It is therefore very important not to grant access to any site, but only to trusted sites. Here the CORS policy allows credentials to pass in cross-origin requests made using scripts. The reason for this being "Access-Control-Allow-Credentials: true" header set in the response header for CORS requests. It is possible to construct requests using scripts to make transactions in target and trick users to execute it in their browsers having valid sessions. When a web server is designed to receive a request from a client without any mechanism for verifying that it was intentionally sent, then it might be possible for an attacker to trick a client into making an unintentional request to the webserver which will be treated as an authentic request.

**Affected URL/API(s)**
https://<host>:8443/ec-exchange/v1

**Request/Response** 
Request:
GET /ec-exchange/v1/orgs/<host>/users HTTP/1.1
Authorization: Basic cm9vdC9yb290OkpISmk4ZlkzQ1RUcGh4MlluQjNLUW0zZWFERDJibw== User-Agent: PostmanRuntime/7.15.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 36bf3250-99a4-4c28-9c18-0f096991d4d2
Host: <host>:8443
Accept-Encoding: gzip, deflate
Connection: close
_Origin: https://attacker.com_

Response:
HTTP/1.1 200 OK
Date: Tue, 23 Jul 2019 09:43:50 GMT Content-Type: application/json;charset=utf-8 Connection: close
_Access-Control-Allow-Origin: https://attacker.com
Access-Control-Allow-Credentials: true_
Access-Control-Max-Age: 1800
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,HEAD,OPTIONS,PATCH X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Length: 1137
{"users":{"<host>- cluster/admin1":{"password":"$2a$10$g1pJ938cdcTdX01vmbrYn.lmqCvWpeTcIOa2.TTna5sXWCo0H 1uQy","admin":true,"email":"<redacted","lastUpdated":"2019-07- 23T09:43:24.294Z[UTC]","updatedBy":"root/root"},"<host>/user2":{"password":"","admin":false,"email":"user2","lastUpdated":"2019-07- 18T13:21:34.798Z[UTC]","updatedBy":"<redacted/user2"},"<host>/clusteradmin1":{"password":"","admin":false,"email":"clusteradmin1","lastUpdated":"2019- 07-18T05:34:09.709Z[UTC]","updatedBy":"<host>/clusteradmin1"},"<host>/admin":{"password":"","admin":false,"email":"admin","lastUpdated":"2019-07- 18T00:53:52.322Z[UTC]","updatedBy":"<host>/admin"},"<host>/user1":{"password":"","admin":false,"email":"user1","lastUpdated":"2019-07- 18T01:17:17.733Z[UTC]","updatedBy":"<host>/user1"},"<host>/testuser1":{"password":"$2a$10$bB1vSbfm1nDMf.hs4K7ygeoM9FqMMGYmXdxCxfWg45BdS odXhnQ3.","admin":true,"email":"<redacted","lastUpdated":"2019-07- 22T11:07:41.787Z[UTC]","updatedBy":"root/root"}},"lastIndex":0}

**Risk Assessment**
If the user is currently logged in to the victim site, the request will automatically use the user's credentials including session cookies, IP address, and other browser authentication methods. Using this method, the attacker forges the victim's identity and submits actions on his or her behalf.

**Fix Recommendation**
Disable credentials for cross-origin requests
Set "Access-Control-Allow-Credentials: false" for all services
Any inappropriate domains should be removed from the CORS policy.
Prepare a list of trusted sites, and set them as the value of the "Access-Control-Allow-Origin" header

**Comment by bmpotter** [comment]
According to chris, this did not show up in the recent scan, so is fixed with the akka version of the exchange.
