### ISSUE TITLE
Add number of unregister nodes to /admin/status output

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/exchange-api#201]
So customers can easily see nodes that are "unused".

**Comment by sf2ne** [comment]
Go to here in the code: https://github.com/open-horizon/exchange-api/blob/master/src/main/scala/com/horizon/exchangeapi/AdminRoutes.scala#L270

And add another db.run() step to query the database for the number of registered nodes.
Then include that in the response body like this:
```
{
  "msg": "string",
  "numberOfUsers": 0,
  "numberOfNodes": 0,
  "numberOfRegisteredNodes": 0.
  "numberOfNodeAgreements": 0,
  "numberOfNodeMsgs": 0,
  "numberOfAgbots": 0,
  "numberOfAgbotAgreements": 0,
  "numberOfAgbotMsgs": 0,
  "dbSchemaVersion": 0
}
```

**Comment by megha070** [comment]
@sf2ne So I just noticed that the issue title says we need to find the unregistered nodes. Just wanted to confirm do we need to include both of them? Also, If we are finding the registered node for this particular API so will it be for the entire exchange server?

**Comment by sf2ne** [comment]
@megha070 Sorry I mistyped you should be adding the number of unregistered nodes. And yes for this particular API it would be for the whole exchange server as we don't specify org anywhere.

**Comment by naphelps** [comment]
Added feature in v2.126.0.
