### ISSUE TITLE
hzn exchange node update (PATCH) wipes out registeredServices if input bad

### ISSUE THREAD

**Issue by dabooz** [open-horizon/exchange-api#213]
what i passed was this:
[
      {
        "inputs": [
          {
            "name": "var1",
            "value": "someString"
          },
          {
            "name": "var2",
            "value": 5
          },
          {
            "name": "var3",
            "value": 22.2
          }
        ],
        "serviceArch": "amd64",
        "serviceOrgid": "IBM",
        "serviceUrl": "https://bluehorizon.network/services/netspeed",
        "serviceVersionRange": "[2.2.0,INFINITY)"
      }
]
without the userInput field name, it should have been
{"userInput": [
      {
        "inputs": [
          {
            "name": "var1",
            "value": "someString"
          },
          {
            "name": "var2",
            "value": 5
          },
          {
            "name": "var3",
            "value": 22.2
          }
        ],
        "serviceArch": "amd64",
        "serviceOrgid": "IBM",
        "serviceUrl": "https://bluehorizon.network/services/netspeed",
        "serviceVersionRange": "[2.2.0,INFINITY)"
      }
]}
Sadiyah Faruk:
Did you get an “error parsing input json” message in the response?
Just wondering if it triggers that
David Booz
No. Here's a snippet of what happened:
root@0ae4b72b1db1:/tmp# hzn exchange -v node update -f userinput.json -o userdev an12345 && hzn exchange -v node list -o userdev an12345
[verbose] Config file does not exist: /etc/horizon/hzn.json.
[verbose] Config file does not exist: /etc/default/horizon.
[verbose] Config file does not exist: /root/.hzn/hzn.json.
[verbose] No project level configuration file found.
[verbose] Config file does not exist: /tmp/hzn.json.
[verbose] The exchange url: http://exchange-api:8080/v1
[verbose] GET http://exchange-api:8080/v1/orgs/userdev/nodes/an12345
[verbose] HTTP code: 200
[verbose] The exchange url: http://exchange-api:8080/v1
[verbose] PATCH http://exchange-api:8080/v1/orgs/userdev/nodes/an12345
[verbose] HTTP code: 201
Node an12345 updated in the Horizon Exchange.
[verbose] Config file does not exist: /etc/horizon/hzn.json.
[verbose] Config file does not exist: /etc/default/horizon.
[verbose] Config file does not exist: /root/.hzn/hzn.json.
[verbose] No project level configuration file found.
[verbose] The exchange url: http://exchange-api:8080/v1
[verbose] GET http://exchange-api:8080/v1/orgs/userdev/nodes/an12345
[verbose] HTTP code: 200
{
  "userdev/an12345": {
    "arch": "amd64",
    "lastHeartbeat": "2019-09-10T20:34:58.772Z[UTC]",
    "msgEndPoint": "",
    "name": "anaxdev",
    "owner": "userdev/useranax1",
    "pattern": "",
    "publicKey": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAruUJSxJfO0EexnsSIfBOEEDesgEkvSXE45//gPta4FsB7JsAooKpM4LFFr5p2T0agsrRYmVzx0Q8bd7m+sxdbhqk5q6g+aa/GPLUwGv6gUPDj0elTi8I8TgIW2vCByR8W3KsOIZRtiQN1KiIVEjiUFc+MI1cVfdr/M+iJYklmqNxMAbo2FV6f9vTyRl29tZBbBFUidTL0rdY09NnnTh5P5n31ZeT0JqDjEEkPbu0UQyUbkxEAo61YDv4HXueakGBamIBApc0uce36omTqfybj5uADVX7pCTzAwEKHDSjwRv6bV1i27Ojl9P74Fj14ikR360ASg8TvyAbgJzTePBP9QIDAQAB",
    "registeredServices": [],
    "softwareVersions": {},
    "token": "********",
    "userInput": [
      {
        "inputs": [

Before this call was made, the node looked like this:
{
  "userdev/an12345": {
    "arch": "amd64",
    "lastHeartbeat": "2019-09-10T20:29:23.387Z[UTC]",
    "msgEndPoint": "",
    "name": "anaxdev",
    "owner": "userdev/useranax1",
    "pattern": "",
    "publicKey": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAruUJSxJfO0EexnsSIfBOEEDesgEkvSXE45//gPta4FsB7JsAooKpM4LFFr5p2T0agsrRYmVzx0Q8bd7m+sxdbhqk5q6g+aa/GPLUwGv6gUPDj0elTi8I8TgIW2vCByR8W3KsOIZRtiQN1KiIVEjiUFc+MI1cVfdr/M+iJYklmqNxMAbo2FV6f9vTyRl29tZBbBFUidTL0rdY09NnnTh5P5n31ZeT0JqDjEEkPbu0UQyUbkxEAo61YDv4HXueakGBamIBApc0uce36omTqfybj5uADVX7pCTzAwEKHDSjwRv6bV1i27Ojl9P74Fj14ikR360ASg8TvyAbgJzTePBP9QIDAQAB",
    "registeredServices": [
      {
        "configState": "active",
        "numAgreements": 0,
        "policy": "",
        "properties": [],
        "url": "e2edev@somecomp.com/https://bluehorizon.network/services/netspeed"
      },
      {
        "configState": "active",
        "numAgreements": 0,
        "policy": "",
        "properties": [],
        "url": "e2edev@somecomp.com/https://bluehorizon.network/services/network"
      },
      {
        "configState": "active",
        "numAgreements": 0,
        "policy": "",
        "properties": [],
        "url": "e2edev@somecomp.com/https://bluehorizon.network/services/network2"
      },
      {
        "configState": "active",
        "numAgreements": 0,
        "policy": "",
        "properties": [],
        "url": "e2edev@somecomp.com/https://bluehorizon.network/service-cpu"
      },
      {
        "configState": "active",
        "numAgreements": 0,
        "policy": "",
        "properties": [],
        "url": "IBM/https://bluehorizon.network/service-cpu"
      }
    ],
    "softwareVersions": {},
    "token": "********",
    "userInput": [
      {
        "inputs": [
          {
            "name": "var1",
            "value": "someString"
          },
          {
            "name": "var2",
            "value": 5
          },
          {
            "name": "var3",
            "value": 22.2
          }
        ],
        "serviceArch": "amd64",
        "serviceOrgid": "IBM",
        "serviceUrl": "https://bluehorizon.network/services/netspeed",
        "serviceVersionRange": "[2.2.0,INFINITY)"
      },
      {
        "inputs": [
          {
            "name": "var1",
            "value": "node_String"
          },
          {
            "name": "var2",
            "value": 20
          },
          {
            "name": "var3",
            "value": 23.2
          }
        ],
        "serviceArch": "amd64",
        "serviceOrgid": "e2edev@somecomp.com",
        "serviceUrl": "https://bluehorizon.network/services/netspeed",
        "serviceVersionRange": "2.2.0"
      },
      {
        "inputs": [
          {
            "name": "cpu_var1",
            "value": "ibmnodevar1"
          }
        ],
        "serviceArch": "amd64",
        "serviceOrgid": "IBM",
        "serviceUrl": "https://bluehorizon.network/service-cpu",
        "serviceVersionRange": "[0.0.0,INFINITY)"
      },
      {
        "inputs": [
          {
            "name": "cpu_var1",
            "value": "e2edevnodevar1"
          }
        ],
        "serviceArch": "amd64",
        "serviceOrgid": "e2edev@somecomp.com",
        "serviceUrl": "https://bluehorizon.network/service-cpu",
        "serviceVersionRange": "1.0.0"
      }
    ]
  }
}

**Comment by sf2ne** [comment]
Verifying on MP:
```
sadiyahfaruk@sadiyahs-mbp exchange-api % curl --write-out \\n%{http_code} -X PATCH -sS -u "<creds>" "https://9.30.210.34:8443/ec-exchange/v1/orgs/major-peacock-icp-cluster/nodes/sadiyahnodejan22" -H "accept: application/json" -H "Content-Type: application/json" -d "@test_patch.json" | jq
{
  "code": "invalid-input",
  "msg": "Cannot deserialize instance of `com.horizon.exchangeapi.PatchNodesRequest` out of START_ARRAY token\n at [Source: (String)\"[  {    \"inputs\": [      {        \"name\": \"var1\",        \"value\": \"someString\"      },      {        \"name\": \"var2\",        \"value\": 5      },      {        \"name\": \"var3\",        \"value\": 22.2      }    ],    \"serviceArch\": \"amd64\",    \"serviceOrgid\": \"IBM\",    \"serviceUrl\": \"ibm.gps\",    \"serviceVersionRange\": \"[2.2.0,INFINITY)\"  }]\"; line: 1, column: 1]"
}
400
```
test_patch.json:
```
[
  {
    "inputs": [
      {
        "name": "var1",
        "value": "someString"
      },
      {
        "name": "var2",
        "value": 5
      },
      {
        "name": "var3",
        "value": 22.2
      }
    ],
    "serviceArch": "amd64",
    "serviceOrgid": "IBM",
    "serviceUrl": "ibm.gps",
    "serviceVersionRange": "[2.2.0,INFINITY)"
  }
]
```
