### ISSUE TITLE
Add API for all properties used within an Org's exchange

### ISSUE THREAD

**Issue by paysl-johnl** [open-horizon/exchange-api#216]
As a user, when I'm working in my edge environment I need to know what are the valid properties within my Org so that the system can autosuggest to help me remember them and reduce potential errors.

**Comment by sf2ne** [comment]
Need to discuss with UI team about the exact structure of the new API route(s).
- Do we want it to be three routes (one for services, one for buspols, and one for nodes) or one route for all the information?
- How much information from the properties do we want? (name, type, value)

**Comment by sf2ne** [comment]
Closing this issue as it was moved to: https://github.com/open-horizon/exchange-api/issues/368
