### ISSUE TITLE
Wrong error message when wrong organization is specified

### ISSUE THREAD

**Issue by linggao** [open-horizon/exchange-api#221]
Try to get a pattern from a different organization but misspelled the pattern org name. The credential entered is correct, but the pattern org name is mis-spelled. The error message does not make sense. 
````
GET v1/orgs/IBM1/patterns/pattern-ibm.helloworld, output: {"code":"access-denied","msg":"Access denied: 'myorg/user' does not have authorization: READ_OTHER_ORGS"}
````
If I change the org from 'IBM1' to `IBM`, the exchange returns the pattern.

**Comment by bmpotter** [comment]
Sadiyah,

In the authorization check code, when it concludes that the request's org is not my cred's org, it should also check the org cache (a new cache) to see if the org exists, and i that case return a better msg.

**Comment by bmpotter** [comment]
This is the same code issue as https://github.com/open-horizon/exchange-api/issues/256, so i combined this issue into that.
