### ISSUE TITLE
Swagger section of `POST /orgs/{orgid}/search/nodes/service` not correct

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#228]
Namely this line `val postServiceSearch2 = (apiOperation[PostNodeHealthRequest]("postSearchNodeHealth2") summary("a") description("a"))` references the wrong request it should be
`val postServiceSearch2 = (apiOperation[PostServiceSearchRequest]("postServiceSearch2") summary("a") description("a"))`

Also both of the log statements:
```
logger.debug("POST /orgs/"+orgid+"/search/nodehealth criteria: "+searchProps.toString)
logger.debug("POST /orgs/"+orgid+"/services/"+service+"/search result size: "+list.size)
```
have the wrong descriptors.

**Comment by bmpotter** [comment]
This was fixed as part of the conversion to akka-http
