### ISSUE TITLE
Pattern Search "service not in pattern" response improperly formatted

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#229]
This line in PatternsRoutes.scala:
```else DBIO.failed(newThrowable(ExchangeMessage.translateMessage("service.not.in.pattern"))).asTry```
forgets to add the parameters for the message. 
This is what the original line was:
```//else DBIO.failed(new Throwable("the serviceUrl '"+searchSvcUrl+"' specified in search body does not exist in pattern '"+compositePat+"'")).asTry```
So the line should be:
```else DBIO.failed(newThrowable(ExchangeMessage.translateMessage("service.not.in.pattern", searchSvcUrl, compositePat))).asTry```

**Comment by mikehyde** [comment]
Please assign p1, 2, or 3 tag.

**Comment by sf2ne** [comment]
Verified on better-tapir:
```
sadiyahfaruk@sadiyahs-mbp exchange-api % curl -X POST -sS -u "<auth>" "<better-tapir-url>/ec-exchange/v1/orgs/mycluster/patterns/pattern-img-class-amd64/search" -H "accept: application/json" -H "Content-Type: application/json" -d "@pattern_search.json" | jq
{
  "code": "invalid-input",
  "msg": "invalid input: the serviceUrl 'mycluster/fake.fakefake' specified in search body does not exist in pattern 'mycluster/pattern-img-class-amd64'"
}
```
