### ISSUE TITLE
Disable exchange org verification for ICP IAM authentication

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/exchange-api#231]
An ibmer found a bug in exchange icp auth when icp was installed with the cluster domain **not** being the typical `<cluster-name>.icp`. (The current `verifyOrg()` for the iamapikey case depends on that.) In the course of the conversation with carl, we concluded that in the icp case, the verifyOrg wasn't necessary (it was mostly a holdover from the public cloud auth). So do the following:

* In `auth/IbmCloudModule:verifyOrg()` just return `DBIO.successful(authInfo.org)` in both of the icp cases (iamtoken and iamapikey). And comment out `extractICPOrg()` which is no longer needed.
* Make this change in both the `master` and `v3.2.1` branches:
  * In the master branch it should be version `1.117.0`
  * In the v3.2.1 branch it should be version `1.116.1`
* Test the `1.116.1` version on icp 3.2.0 and 3.2.1 (have carl or chris help you). If possible, the icp 3.2.1 test should be in a cluster in which the domain has been set to something other than `<cluster-name>.icp`.

**Comment by sf2ne** [comment]
Version 1.116.1 verified by @edgedock
