### ISSUE TITLE
Handle exchange upgrade under load via graceful termination

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/exchange-api#237]
In the scalatra version, when the exchange was upgraded during a scale test the db was giving: invalid chunk number (and something about toast).

- [x] Set the akka setting for graceful termination setting: https://doc.akka.io/docs/akka-http/current/server-side/graceful-termination.html

**Comment by bmpotter** [comment]
Doug, i need you to test this on the scale cluster, but this is lower priority than the primary scale tests

**Comment by sf2ne** [comment]
Verified by Doug in scale testing
