### ISSUE TITLE
invalid message when publishing a pattern to the exchange with an incorrect -u userPw

### ISSUE THREAD

**Issue by jiportilla** [open-horizon/exchange-api#241]
For example:

hzn exchange pattern publish -f horizon/pattern.json -u iamapikey:rMyyN

....
Error: bad HTTP code 401 from GET https://9.30.210.34:8443/ec-exchange/v1/orgs/major-peacock-icp-cluster/patterns/pattern-rpi-rpi.ibm.holaworld-arm, output: {"code":"invalid-credentials","msg":"error authenticating ICP IAM API key: No usable value for sub\nDid not find value which can be converted into java.lang.String"}

**Comment by mikehyde** [comment]
Please label p1, p2, or p3.

**Comment by bmpotter** [comment]
Ivan,

This is already fixed in exchange version 1.118.0. Please have chris update the exchange on the cluster you are using, and try this again.

**Comment by jiportilla** [comment]
tested with new exchange version and it works as intended, closing this issue

hzn exchange pattern publish -f horizon/pattern.json -u iamapikey:rMyyN
Error: bad HTTP code 401 from GET https://9.30.210.34:8443/ec-exchange/v1/orgs/major-peacock-icp-cluster/patterns/pattern-rpi.ibm.holaworld-arm, output: {"code":"invalid-credentials","msg":"invalid API key"}
