### ISSUE TITLE
POST service api allows empty "type"

### ISSUE THREAD

**Issue by varatep** [open-horizon/exchange-api#250]
The `POST` service api currently allows an empty `type` value inside of the `userInput` property array. This should either verify that it's not blank or default it to `string`.

![image (4)](https://user-images.githubusercontent.com/3941301/68903804-16586c00-06f1-11ea-81e9-5e54aafd9bd7.png)

**From Ling:** anax checks the userinput type against the type defined in the service, and the code does not assume the type is string if empty.

**Comment by bmpotter** [comment]
This is being addressed at the anax level by ling in issue https://github.com/open-horizon/anax/issues/1432
