### ISSUE TITLE
Get pattern from different org gives wrong error message.

### ISSUE THREAD

**Issue by linggao** [open-horizon/exchange-api#256]
Exchange version 1.121.0.
```
hzn exchange pattern list -u myorg/myid:mypasswed e2edev@somecomp.com/pattern_name
```
If the pattern exists, the pattern is retrieved without problem. However, if the pattern does not exist, it gives the following error which is confusing.
```
Error: bad HTTP code 403 from GET http://exchange-api:8080/v1/orgs/e2edev@somecomp.com/patterns/pattern_name, output: {"code":"access-denied","msg":"Access denied: 'userdev/userdevadmin' does not have authorization: READ_OTHER_ORGS"}
```

A very similar problem is when the org is mistyped:

```
GET v1/orgs/IBM1/patterns/pattern-ibm.helloworld, output: {"code":"access-denied","msg":"Access denied: 'myorg/user' does not have authorization: READ_OTHER_ORGS"}
```

**Comment by bmpotter** [comment]
The error msgs has been improved slightly:
```
$ hzn exchange pattern list -u "mycluster/$HZN_EXCHANGE_USER_AUTH" IBM/foo
Error: bad HTTP code 403 from GET http://localhost:8080/v1/orgs/IBM/patterns/foo, output: {"code":"access-denied","msg":"Access denied: 'mycluster/admin' does not have authorization: READ_OTHER_ORGS pattern=IBM/foo"}
```

It is difficult for the exchange authentication logic to distinguish between these 2 cases when trying to access a resource in a different org:
1. the resource is not public (returns 403 - access denied)
2. the resource doesn't exist (currently returns 403 - access denied, but 404 - not found might be better)

So might push this off to the next release

**Comment by bmpotter** [comment]
Sadiyah, please test/verify

**Comment by jiportilla** [comment]
tested & verified with

hzn exchange pattern list -u mycluster/iamapikey:asdfa  mycluster/pattern-boulder-ibm.holaworld
Error: pattern 'pattern-boulder-ibm.holaworld' not found in org mycluster


hzn exchange pattern list -u mycluster/iamapikey:asdfasdf  mycluster2/pattern-boulder-ibm.holaworld-amd64
Error: pattern 'pattern-boulder-ibm.holaworld-amd64' not found in org mycluster2


 hzn exchange pattern list -u mycluster/iamapikey:asdf  mycluster/pattern-boulder-ibm.holaworld-amd64
{
  "mycluster/pattern-boulder-ibm.holaworld-amd64": {
    "owner": "mycluster/admin",
    "label": "Edge ibm.holaworld Service Pattern for amd64",
    "description": "Pattern for ibm.holaworld for amd64",
    "public": false,
    "services": [
      {
        "serviceUrl": "ibm.holaworld",
        "serviceOrgid": "mycluster",
        "serviceArch": "amd64",
        "serviceVersions": [
          {
            "version": "1.0.1",
            "priority": {},
            "upgradePolicy": {}
          }
        ],
        "dataVerification": {
          "metering": {}
        },
        "nodeHealth": {
          "missing_heartbeat_interval": 1800,
          "check_agreement_status": 1800
        }
      }
    ],
    "agreementProtocols": [
      {
        "name": "Basic"
      }
    ],
    "lastUpdated": "2020-01-29T17:45:47.201Z[UTC]"
  }
}
