### ISSUE TITLE
Fixes for Notification Framework

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#258]
- [x] Change query so that it gets public changes from all orgs not just IBM org
- [x] Add `maxChangeIdOfQuery` to response body
- [x] Collate by id and resource fields
- [x] take out unnecessary write in response - Bruce did this in the akka PR

**Comment by bmpotter** [comment]
Dave, i think you have already confirmed this in your use of it in the latest anax. If that's true, please comment here and close. Thx.

**Comment by dabooz** [comment]
The PR for https://github.com/open-horizon/anax/issues/1311 required these fixes and verified that no more fixes were needed.
