### ISSUE TITLE
Exchange calls to https://<icp>/api/v1/config to avoid 502 gateway timeouts 

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/exchange-api#262]
Driven from the Edge UI, calls are made to

```
2020-01-07 12:31:27,954 [qtp578866604-9397] ERROR EXCHANGE - User or id iec-scale-test7-icp-cluster/iamtoken from 10.1.104.255 running GET /orgs/iec-scale-test7-icp-cluster/nodes/edge-scale-test179_horizon3/status: invalid-credentials:
```

which results in REST calls to
```
2020-01-07 12:31:27,954 [scala-execution-context-global-9462] INFO  EXCHANGE - Attempt 5 retrieving ICP IAM cluster name from https://icp-management-ingress.kube-system:8443/api/v1/config
```

If there are many agents registered, this API call can overwhelm the ICP endpoint and return a `502 Bad Gateway` response.

However, the response to `https://icp-management-ingress.kube-system:8443/api/v1/config` is something like
```
{"cluster_name":"iec-scale-test7-icp-cluster","cluster_url":"https://9.46.83.210:8443","cluster_ca_domain":"iec-scale-test7-icp-cluster.icp","kube_url":"https://9.46.83.210:8001","helm_host":"9.46.83.210:31514","cli_build":"v3.2.1-1356","cli_revision":"71ca70f764a8bac9d98213574e5d20515a231d70"}
```

And the cluster name will never change according to ICP documentation.

Since the cluster name never changes, an optimization would be for the exchange servers to make this api call on initialization, store it off, and never make it again.  The code making this call is in exchange-api/src/main/scala/com/horizon/exchangeapi/auth/IbmCloudModule.scala#verifyOrg

The above optimization will eliminate returning an error (when many agents are registered) to the UI when the page loads or refresh is pressed which results in making this API call
```
GET /orgs/iec-scale-test7-icp-cluster/nodes/edge-scale-test179_horizon3/status
```

**Comment by dlarson04** [comment]
This one might be a good use case to first fix the issue where `invalid-credentials` and likely a 401 is mistakenly returned to the caller when it is not a real 401 since this one is fairly easy to reproduce by having say 100 agents registered and using the edge ui.  Something like a 503 service unavailable could be returned by exchange so clients can retry. Currently, since a 401 is returned, the clients would not consider that a retryable error code.

**Comment by bmpotter** [comment]
Doug, I need you to test/verify this fix, but it's lower priority than the primary scale testing

**Comment by dlarson04** [comment]
Verifying this issue with 2.12.3 version of exchange. When accessing the  UI, I don't see any calls to the API to get the cluster name
