### ISSUE TITLE
Move exchange up to openjre 11

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/exchange-api#267]
Currently when sbt builds the dockerfile, it uses `FROM openjdk:8-jre`. This can be controlled in the settings for the sbt-native-packager plugin building the docker image. See: https://sbt-native-packager.readthedocs.io/en/stable/formats/docker.html

Does this mean we also have to move to akka 2.6.x ? (2.6.0 was only released in 11/2019, as of 1/2020 2.6.3 is out)

**Comment by naphelps** [comment]
Splitting any Akka changes into its own issue: #423.
