### ISSUE TITLE
Static Scan Result - Errors unhandled for Validation.Required.URL

### ISSUE THREAD

**Issue by aonafowora** [open-horizon/exchange-api#292]
The most recent static scan of Exchange API has returned the following issue:

Description:  Potential use of variable for URL detected in src\src\test\go\perfutils\perfutils.go.  The referenced line numbers are 416, 516, and 598.

Source File and Line: `src\test\go\perfutils\perfutils.go` 416

You can find the full report here:  https://ibm.ent.box.com/file/609697888253

**Comment by bmpotter** [comment]
The referenced file (`src\test\go\perfutils\perfutils.go`) is only used internally to ibm, for scale tests during development, so this is not a security exposure.
