### ISSUE TITLE
Dynamic Scan Result - Incomplete or No Cache-control and Pragma HTTP Header Set

### ISSUE THREAD

**Issue by aonafowora** [open-horizon/exchange-api#293]
The most recent dynamic scan of the Exchange API has returned the following issue:

Description:  The cache-control and pragma HTTP header have not been set properly or are missing allowing the browser and proxies to cache content.

URL: GET https://<cluster-url>/ec-exchange/v1/admin/version

Given Solution from the Tool:  Whenever possible ensure the cache-control HTTP header is set with no-cache, no-store, must-revalidate; and that the pragma HTTP header is set with no-cache.

You can find the full report here:  https://ibm.ent.box.com/file/607463162828

**Comment by bmpotter** [comment]
We already discussed this on our security slack channel and agreed that the `/admin/version` api doesn't return any sensitive info (only the exchange version number), so we don't need to set cache-control.
