### ISSUE TITLE
Determine if exchange src/main/webapp can be deleted

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/exchange-api#294]
The content in `src/main/webapp` is from the scalatra version of the exchange and can be deleted. The swagger UI files are now put in `src/main/resources/swagger` so they can be loaded by `SwaggerDocService.scala:SwaggerUiService`

**Comment by sf2ne** [comment]
Both the scale environments and better-tapir used exchange 2.15.1 and verified it worked.
