### ISSUE TITLE
GET /orgs/<orgid>/business/policies incorrectly returns 404 when a user tries to access policies from a different org

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#301]
This is part of Epic 218
Currently:
```curl -X GET -sS -w %{http_code} -u "Sadiyah.Faruk@ibm.com/wrongorguser:abc123doremi" "http://localhost:8080/v1/orgs/org2/business/policies" -H "accept: application/json" -H "Content-Type: application/json" | jq```
returns 
```
{
  "businessPolicy": {},
  "lastIndex": 0
}
404
```
Should return 
```
{
  "code": "access-denied",
  "msg": "access-denied"
}
403
```

**Comment by linggao** [comment]
Looks like this one is fixed.
