### ISSUE TITLE
Change policy property type from 'list of string' to 'list of strings'

### ISSUE THREAD

**Issue by linggao** [open-horizon/exchange-api#307]
Anax has changed the supported policy property type from "list of string" to "list of strings".  This will affect node policy, business policy and service policy. Please make the corresponding changes in these resources in the exchange. 
Here is an error example with exchange version 2.12.3.
````
$hzn exchange service addpolicy -f sp_linghello_1.json linghello_0.0.1_amd64
...
Error: bad HTTP code 400 from PUT https://icp-console.apps.better-tapir.purple-chesterfield.com/ec-exchange/v1/orgs/mycluster/services/linghello_0.0.1_amd64/policy: invalid-input, The properties.type value 'list of strings' must be 1 of: float, string, version, boolean, int, list of string
````

**Comment by sf2ne** [comment]
Verified on staging and by anax
