### ISSUE TITLE
Create swagger.json during build so it can be in KC

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/exchange-api#318]
The Knowledge Center can format/display swagger.json files, so this can be used to display the exchange swagger. See the [MMS API](https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_4.1/devices/developing/mms_swagger.json) for example. (The current open source code to display the exchange swagger has many security vulnerabilities, which is why we don't expose it yet).

- [ ] For customers, need to be able to subset the routes that are included in swagger, so we don't document any of the "dangerous" routes (e.g. `POST /admin/dropdb`). Make a list with booz and bruce that should be omitted from the customer swagger.
- [ ] If you don't have a better way to create a subset of the swagger info, you could use a script with `jq` commands like this to delete routes:

```
newJson="$json"
for r in $routes; do
    newJson=$(jq -c ".paths | del(.$r.owner)" <<< $newJson)
done
```

Once this subset of `swagger.json` is ready, i can commit it to the `Edge-Fabric/docs` git repo.

Note: This should be done for the 4.1 swagger and the 4.2 swagger

**Comment by sf2ne** [comment]
This route doesn't contain supporting multiple APIs, it only contains manually adjusting the swagger.json file and adding that to the KC
