### ISSUE TITLE
Onboarding Education

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#328]
- [x] Scala - https://yourlearning.ibm.com/#activity/EELC-SAFARI9780133430127
- [x] Akka (our framework) - https://yourlearning.ibm.com/#activity/EELC-SAFARI9781800204454
- [x] Functional Programming (in Scala) - https://yourlearning.ibm.com/#activity/SKILLSOFT-4583A5E4-0E69-11E7-B952-0242C0A80B07
- [x] Postgresql - https://yourlearning.ibm.com/#activity/EELC-SAFARI0735711216
- [x] KC 4.0 Docs: https://www.ibm.com/support/knowledgecenter/SSFKVV_4.0/devices/installing/adding_devices.html
- [x] IEAM `learn.cloud.ibm` class: https://learn.ibm.com/course/view.php?id=6033#section-2

**Comment by naphelps** [comment]
Scala complete.

**Comment by naphelps** [comment]
Functional Programming (in Scala) completed.

**Comment by naphelps** [comment]
Akka completed.

**Comment by naphelps** [comment]
Completed.
