### ISSUE TITLE
ExchangeAPI in docker cannot find the config file

### ISSUE THREAD

**Issue by Nitu-coder** [open-horizon/exchange-api#339]
When i m running the exchange api -server  in docker, I m nt able to find the config.json file, though its present.  When i check using a simple scala code, it gives me file present.
I have attached the screenshots of file presence and the logs 
![logs_openhorizon](https://user-images.githubusercontent.com/43419655/78678788-0bec7800-7907-11ea-8b0f-33942b63f14f.png)
![config json](https://user-images.githubusercontent.com/43419655/78678796-0ee76880-7907-11ea-9d5c-b4dd901d4ace.png)

**Comment by sf2ne** [comment]
Hello! Could you please run `ls -l` on the host `etc/horizon/exchange` directory and also docker exec into the docker container and run `ls -l` on `etc/horizon/exchange` there too.

**Comment by Nitu-coder** [comment]
> Hello! Could you please run `ls -l` on the host `etc/horizon/exchange` directory and also docker exec into the docker container and run `ls -l` on `etc/horizon/exchange` there too. Also could you run `docker inspect $(docker ps -q --filter name=exchange-api) | jq '.[0].Mounts'` to see if everything mounted properly.

I have attached the screenshots for the command executed. It seems to be a mount issue. There is no directory /etc/horizon/exchange in the docker. Also the inspect command gives a empty array.
Can you please help me with this issue as in why this mount issue is existing.

Also one more query can the exchange api server run without docker?? If so then what is the comamnd to run it normal mode

**Comment by sf2ne** [comment]
Hello again, we tested again and were able to successfully mount `/etc/horizon/exchange`, so we believe the issue may be related to some permissions of items in `/etc/horizon/exchange` on the host. In addition, you can run the exchange locally without docker.  If you refer to our [README](https://github.com/open-horizon/exchange-api/blob/master/README.md) specifically the sections [Preconditions for Local Development](https://github.com/open-horizon/exchange-api/blob/master/README.md#preconditions-for-local-development) and [Building and Running in Local Sandbox](https://github.com/open-horizon/exchange-api/blob/master/README.md#building-and-running-in-local-sandbox) describe how to get the exchange running locally using sbt.

**Comment by Nitu-coder** [comment]
> Hello again, we tested again and were able to successfully mount `/etc/horizon/exchange`, so we believe the issue may be related to some permissions of items in `/etc/horizon/exchange` on the host. In addition, you can run the exchange locally without docker. If you refer to our [README](https://github.com/open-horizon/exchange-api/blob/master/README.md) specifically the sections [Preconditions for Local Development](https://github.com/open-horizon/exchange-api/blob/master/README.md#preconditions-for-local-development) and [Building and Running in Local Sandbox](https://github.com/open-horizon/exchange-api/blob/master/README.md#building-and-running-in-local-sandbox) describe how to get the exchange running locally using sbt.

What kind of permissions are needed to provided and ay changes i need to make it at the host system for it to run???

**Comment by sf2ne** [comment]
So the `/admin/version` endpoint doesn't require a specific user, but all other endpoints would require credentials. When running the exchange locally you should define a root user in `src/main/resources/config.json`. If you want some resources populated in the exchange you can follow the direction in the readme to run `src/test/bash/primedb.sh`. Otherwise if you are using curl to hit the exchange you need to use `-u / --user`. When curling as the root user your curl command can look like this: `curl -X GET -u "root/root:<rootpassword>" "<url>/v1/admin/status" -H "accept: application/json" -H "Content-Type: application/json"`

**Comment by sf2ne** [comment]
Closing this issue as the initial problem was found to not be an exchange bug.
