### ISSUE TITLE
Add labels, license content into docker image builds for Red Hat certification

### ISSUE THREAD

**Issue by cgiroua** [open-horizon/exchange-api#347]
Please see the following issue addressing the anax specific requirements:
https://github.com/open-horizon/anax/issues/1686

A similar (exchange-api specific) set of labels will need to be generated on image build, as well as copying our LICENSE.txt into the same `/licenses` directory location.

**Comment by sf2ne** [comment]
name: amd64_exchange-api
vendor: IBM
summary: Open Horizon exchange-api image
description: Containerized exchange-api
version and release should be grabbed dynamically

**Comment by sf2ne** [comment]
This issue also includes injecting the config.json file as well
