### ISSUE TITLE
Exchange New User Role: Super Admin

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#366]
Epic 264
To support multi-tenancy
- can create a new org
- can create an admin user in that org
- can not touch any other resource in the org
- think about what else we don't want him to do 
- maybe give him permissions to create an agbot for an org (actually adding the agbot is out of scope for this release) --> this might also be done by the org admin
   - probably just need to add this permission anyway
- rethink the name (miniSuperAdmin, Super Admin Lite, Second Line Manager
- relate Super Admin to Cluster Admin? Discuss with Carl, is there really a reason we need to conflate the two?

Detail in 3Q2020 Design Doc

**Comment by mikehyde** [comment]
@sf2ne Please either close this issue (if completed or no longer relevant), or change the release to `Winter` or `Future` Release.

**Comment by mikehyde** [comment]
@sf2ne Please either close this issue (if completed or no longer relevant), or change the release to Winter or Future Release.

**Comment by bmpotter** [comment]
I verified this issue
