### ISSUE TITLE
Support for OpenShift 4.5

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#369]
Epic 273

**Comment by mikehyde** [comment]
@sf2ne Please either close this issue (if completed or no longer relevant), or change the release to `Winter` or `Future` Release.

**Comment by mikehyde** [comment]
@sf2ne Please either close this issue (if completed or no longer relevant), or change the release to Winter or Future Release.

**Comment by bmpotter** [comment]
This has been verified by QA
