### ISSUE TITLE
Unable to run this on Raspberry-pi 4 (ubuntu 20.04)

### ISSUE THREAD

**Issue by sinny777** [open-horizon/exchange-api#381]
I've been trying to run Open-horizon hub service on my Raspberry-pi 4, but its throwing errors related to the architecture docker image is built.  Please let me know if a docker image would be available for Raspberry-pi 4 Arm Architecture ? I'm getting following errors with openhorizon/amd64_exchange-api, openhorizon/amd64_agbot and openhorizon/amd64_cloud-sync-service docker images:

standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by sf2ne** [comment]
So the exchange-api can't be run on arm at the moment, there is only an image available for amd64. The agbot and cloud-sync-service can be built for many architectures. To get more information on that you can look at their README here: https://github.com/open-horizon/anax. They go over it a bit in the `introduction` section. You'll have to use their `horizon-deb-packager` : https://github.com/open-horizon/horizon-deb-packager.

**Comment by sf2ne** [comment]
Closing this issue as the exchange currently only runs on amd64
