### ISSUE TITLE
Exchange OOM possibly due to build up of agbotmsgs

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/exchange-api#387]
I got a scale environment in an unhealthy state where exchanges and agbots were being restarted.. Then I saw an OOM message in the logs for the exchange.

I am not certain but I think it was due to the calls to GET /agbotmsgs as this does a DB query without a limit and there was a ton of agbotmsgs.   One of my recovery actions was to get on the exchangedb and delete all the agbotmsgs.

Normally, this wouldn't be an issue as the agbots read and then delete the messages but in a recovery state, it might prevent an OOM if the response to this API call was limited by adding a limit to the DB query.

The Exchange java heap is 1GB and each message is about 9k so 115k messages would cause an OOM. 

A limit of 10000 messages might prevent an OOM in a recovery state if in fact the call to GET /agbotmsgs was the cause.

I think we will need a limit on this eventually if scaling targets are to continue to increase.

**Comment by sf2ne** [comment]
For now: remove delay on agbot and node msg pruning

**Comment by dlarson04** [comment]
Closing since #440  is opened
