### ISSUE TITLE
The pattern node search api does not validate the workloadUrl

### ISSUE THREAD

**Issue by linggao** [open-horizon/exchange-api#39]
````
 echo '{
  "workloadUrl": "blah",
  "secondsStale": 60,
  "startIndex": 0,
  "numEntries": 0
}' |   curl -sLX POST -H 'Content-Type: application/json' -H 'Accept: application/json' -H "Authorization:Basic  myorg/user:password" --data @- "https://exchangeurl/v1/orgs/myorg/patterns/netspeed-amd64/search" |jq '.'
{
  "nodes": [
    {
      "id": "myorg/myvs1",
      "msgEndPoint": "",
      "publicKey": "..."
    }
  ],
  "lastIndex": 0
}
````
Any string for workloadUrl would result in the device.

**Comment by bmpotter** [comment]
Right. The reason it is returning your node is because this search is essentially "give me all of the nodes that use this pattern, but don't have an agreement for this workload". But i should verify the workloadUrl is part of the pattern to catch typos.

**Comment by bmpotter** [comment]
Will implement this in the `service` resource, so i added this todo to exchange-api issue #51 because it is working on the same code
