### ISSUE TITLE
UI Routes for Multi-tenancy

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#395]
`GET /v1/admin/orgstatus`
For now this route only returns a per-org breakdown of the number of nodes

Example Response Body:
```
{
  "msg": "Exchange server operating normally",
  "nodes": {
    "bp@us.ibm.com": 1,
    "org2": 10,
    "IBM": 2,
    "Sadiyah.Faruk@ibm.com": 1
  }
}
```

`GET /v1/myorgs`
This route returns the org resources that the caller potentially has access too, based on their IAM credentials
Example Response Body:
The same as GET /v1/orgs

**Comment by bmpotter** [comment]
Done
