### ISSUE TITLE
Support GET /v1/orgs/{orgid}/nodes/{id}/msgs/{msgid} and GET /v1/orgs/{orgid}/agbots/{id}/msgs/{msgid}

### ISSUE THREAD

**Issue by MaxMcAdam** [open-horizon/exchange-api#396]
Needed for anax issue https://github.com/open-horizon/anax/issues/1995

**Comment by sf2ne** [comment]
200 if you can get the message, 404 if you can’t find it

**Comment by sf2ne** [comment]
return the messages in a `[]` even if its just one message
