### ISSUE TITLE
POST ​/v1​/orgs​/{orgid}​/agbots​/{id}​/agreements​/confirm wrong in swagger

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#418]
~~This route gives out this error message: `"method not supported: DELETE or GET or PUT"`
Investigate why and solve.~~

This is because the route is defined wrong in swagger. The route is actually `POST /orgs/{orgid}/agreements/confirm`. The route needs to be fixed in swagger.

**Comment by bmpotter** [comment]
Fixed in https://github.com/open-horizon/exchange-api/pull/471 .
