### ISSUE TITLE
Investigate all exchange timeouts

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#432]
- [x] Akka timeout `akka.http.server.request-timeout` -- default is 20 seconds? (This was fixed in https://github.com/open-horizon/exchange-api/issues/456 )
- [ ] Postgres timeout?
- [ ] Ingress timeout
- [ ] Timeout passed in from header (is this the ingress timeout?)

**Comment by dlarson04** [comment]
Update on this issue.
I have been investigating Exchange timeout such as
```
Jan 11 17:43:14 ibm-edge-exchange-66994fd48c-x7nrt  [01/11/2021 22:43:14.026] [actors-akka.actor.default-dispatcher-448] [akka.actor.ActorSystemImpl(actors)] Request timeout encountered for request [PUT /v1/orgs/ieam-roks-scale/nodes/edge-scale-test16_x2_horizon28/agreements/29e1444493d7b3ec2dce1232865fc0adbe1da39f504bb043d9cf664b90ce8eb3 Strict(145 bytes)] 
```
I am convinced this is a timeout controlled by `akka.http.server.request-timeout` which has a default of 20s. I am going to request this get changed to 45s in winter release. Making that change greatly reduces the frequency of these timeout messages in the exchange. I can change this parameter now through the configuration. Note, according to https://doc.akka.io/docs/akka-http/current/configuration.html, says
```
    # Make sure this timeout is smaller than the idle-timeout, otherwise,
    # the idle-timeout will kick in first and reset the TCP connection
    # without a response.
```
and the `idle-timeout` has a default value of 60s
