### ISSUE TITLE
Add support for label and description to node and service policy objects

### ISSUE THREAD

**Issue by dabooz** [open-horizon/exchange-api#435]
In support of issue https://github.com/open-horizon/anax/issues/1667 in the agent, the exchange should accept 2 additional fields in the node and service policy objects to enable users to document those objects. The fields are similar to the label and description fields already supported in a deployment (business) policy.

**Comment by bmpotter** [comment]
Submitted PR https://github.com/open-horizon/exchange-api/pull/457 .

From swagger, the `PUT /orgs/{orgid}/services/{service}/policy` request body is:

```
{
  "label": "human readable name of the service policy",  // this will be displayed in the UI
  "description": "descriptive text",
  "properties": [
    {
      "name": "mypurpose",
      "value": "myservice-testing"
      "type": "string"              // (optional) [boolean, float, int, list of strings, string, version]
    }
  ],
  "constraints": [
    "a == b"
  ]
}
```

(`label` and `description` are optional (can be omitted) for backward compatibility)

The `GET /orgs/{orgid}/services/{service}/policy` response body is:

```
{
  "label": "string",
  "description": "string",
  "properties": [
    {
      "name": "string",
      "type": "string",
      "value": {}
    }
  ],
  "constraints": [
    "string"
  ],
  "lastUpdated": "string"
}
```
