### ISSUE TITLE
Add maxmsgs parameter on GET /msgs calls

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#440]
Add an optional url query parameter called `maxmsgs=<max-num-msgs>` that will limit the number of msgs to that number. (If not specified, the API will return all available msgs.)

The db call the exchange uses should include `sortBy(_.msgId).take(maxmsgs)` to ensure we never return more than the maxmsgs messages number, and that we are returning the oldest messages.

This fix may at least partially resolve anax issue https://github.com/open-horizon/anax/issues/2230 .

**Comment by dlarson04** [comment]
If the limit is enforced, the sort would need to move to the exchangedb so that the agbot would still get the messages in order. This is similar to how the /changes route retrieves changes
