### ISSUE TITLE
Add the configState field to the node status API

### ISSUE THREAD

**Issue by sirotsinskuy** [open-horizon/exchange-api#445]
In support of issue [open-horizon/anax#942](https://github.com/open-horizon/anax/issues/942) in the agent, the exchange should provide additional `configState` field for each of `runningServices` of `the /orgs/{org}/nodes/{id}/status` API. The field should represent the same as it does in `/orgs/{org}/nodes/{id}` API for each of `registeredServices`

In the process, also remove `bluehorizon` from the swagger info. (We've decommissioned that site.)

**Comment by bmpotter** [comment]
Ready for use in `openhorizon/amd64_exchange-api:2.58.0`
