### ISSUE TITLE
Connection refused calling Exchange REST API in All-in-1 environment

### ISSUE THREAD

**Issue by tinkoosingh** [open-horizon/exchange-api#447]
I am getting error : "connection refused calling Exchange REST API" on running any "hzn exchange ..." command

Full error: Encountered HTTP error: Get "http://127.0.0.1:3090/v1/orgs/myorg/services": dial tcp 127.0.0.1:3090: connect: connection refused calling Exchange REST API GET http://127.0.0.1:3090/v1/orgs/myorg/services. HTTP status: .

**Comment by bmpotter** [comment]
You need to provide more information:

1. Is the `exchange-api` container running? Show me the output of `docker ps`
1. when did you run `deploy-mgmt-hub.sh` ?
1. Did you set any specific environment variables before running it?

**Comment by tinkoosingh** [comment]
I have reinstalled the open horizon and it is working fine.
but now I have to reinstall open horizon every time is reboot my system. How to tackle this...?

**Comment by sf2ne** [comment]
Hi @tinkoosingh are you still having the above problems?

**Comment by TheodoreGC** [comment]
I am facing a similar issue.

I can go through the "[what to do next](https://github.com/open-horizon/devops/tree/master/mgmt-hub#-what-to-do-next)" section without any trouble and everything works fine through the CLI tool (`hzn`):

Example with verbose mode enabled:

```sh
$ hzn exchange status -v
[verbose] Reading configuration file: /etc/horizon/hzn.json
[verbose] Reading configuration file: /etc/default/horizon
[verbose] Config file does not exist: /home/theo/.hzn/hzn.json.
[verbose] No project level configuration file found.
[verbose] The exchange url: http://127.0.0.1:3090/v1
[verbose] GET http://127.0.0.1:3090/v1/admin/version
[verbose] HTTP request timeout set to 30 seconds
[verbose] HTTP code: 200
[verbose] The exchange url: http://127.0.0.1:3090/v1
[verbose] GET http://127.0.0.1:3090/v1/admin/status
[verbose] HTTP request timeout set to 30 seconds
[verbose] HTTP code: 200
{
  "dbSchemaVersion": 40,
  "msg": "Exchange server operating normally",
  "numberOfAgbotAgreements": 1,
  "numberOfAgbotMsgs": 0,
  "numberOfAgbots": 1,
  "numberOfNodeAgreements": 1,
  "numberOfNodeMsgs": 0,
  "numberOfNodes": 1,
  "numberOfUsers": 3
}
```

I am trying to query the exchange API without the `hzn` CLI tool and so far I can successfully reach endpoints which don't require authorization. Following the above example:

```sh
$ curl -v http://127.0.0.1:3090/v1/admin/version
*   Trying 127.0.0.1:3090...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3090 (#0)
> GET /v1/admin/version HTTP/1.1
> Host: 127.0.0.1:3090
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: akka-http/10.1.10
< Date: Fri, 02 Apr 2021 08:18:19 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 7
< 
2.63.0
* Connection #0 to host 127.0.0.1 left intact
```

However, I get the same error as @tinkoosingh for endpoints requiring authorization.

When querying `/admin/status`:

```sh
$ curl -v -H "Authorization:Basic $HZN_ORG_ID/$HZN_EXCHANGE_USER_AUTH" http://127.0.0.1:3090/v1/admin/status
*   Trying 127.0.0.1:3090...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3090 (#0)
> GET /v1/admin/status HTTP/1.1
> Host: 127.0.0.1:3090
> User-Agent: curl/7.68.0
> Accept: */*
> Authorization:Basic myorg/admin:<password>
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Server: akka-http/10.1.10
< Date: Fri, 02 Apr 2021 08:21:21 GMT
< Content-Type: application/json
< Content-Length: 58
< 
* Connection #0 to host 127.0.0.1 left intact
{"code":"invalid-credentials","msg":"invalid credentials"}
```

Any ideas what's wrong @sf2ne?

I followed these steps for the installation:

```sh
curl -sSL https://raw.githubusercontent.com/open-horizon/devops/master/mgmt-hub/deploy-mgmt-hub.sh | sudo -i bash
export HZN_ORG_ID=myorg
export HZN_EXCHANGE_USER_AUTH=admin:<password>
```

where `password` is equal to the hashed password generated during the installation.

Environment: Ubuntu 20.04.2 LTS

**Comment by bmpotter** [comment]
@tinkoosingh  The convention for REST APIs is that the basic auth header must be base64 encoded. The exchange-api adheres to this. The easiest way to do this is use the curl `-u` flag, because then curl will encode it for you. Try this:

```
curl -u "$HZN_ORG_ID/$HZN_EXCHANGE_USER_AUTH" http://127.0.0.1:3090/v1/admin/status
```

If this fixes your problem, please comment in this issue and then close it.

**Comment by tinkoosingh** [comment]
yes, it worked. Thanks
