### ISSUE TITLE
The /search api failed to return the node

### ISSUE THREAD

**Issue by linggao** [open-horizon/exchange-api#451]
Six months ago, sometimes nodes were not returned from the policy /search api. There were a number of problems which were confused with this problem, but also logs have since been lost. The situation was:
1) no load on the system
2) user registered a device node with policy, but no agreement was made with the node
3) analysis of the agbot log shows that the /changes API notified the agbot of the node and policy
4) the agbot initiated searches for all policies, but the new node was not returned, subsequent searches by the agbot also did not return the node
5) about 30 mins or so later, another user registered a node with policy, which caused the agbot to initiate a node search
6) both nodes were returned, and agreements were made with both nodes

When looking into problems like this, it is always important to not confuse a problem like this with protocol timeouts on the agbot side. Agbot protocol timeouts occur when the agbot sends a proposal to a node, but never hears back from the node. The agbot will not make any more proposals to that node until the protocol timeout for the original proposal. The default timeout is 10 mins. It is unlikely, but not impossible, for this situation to occur naturally.

**Comment by linggao** [comment]
The last agreement was
````
  {
    "name": "Policy for e2edev@somecomp.com_my.company.com.services.cpu2 merged with Policy for e2edev@somecomp.com_my.company.com.services.hello2 merged with susehello_my.company.com.services.usehello2_e2edev@somecomp.com_amd64",
    "current_agreement_id": "1feeb3359c28a274762f7247dce8a9f7d7bfb61930f2477a4a41b0ade0245eeb",
    "consumer_id": "IBM/ag12345",
    "agreement_creation_time": "2021-01-16 03:09:20 +0000 UTC",
    "agreement_accepted_time": "2021-01-16 03:09:30 +0000 UTC",
    "agreement_finalized_time": "2021-01-16 03:09:31 +0000 UTC",
    "agreement_execution_start_time": "2021-01-16 03:09:34 +0000 UTC",
    "agreement_data_received_time": "",
    "agreement_protocol": "Basic",
    "workload_to_run": {
      "url": "my.company.com.services.usehello2",
      "org": "e2edev@somecomp.com",
      "version": "1.0.0",
      "arch": "amd64"
    },
    "agreement_terminated_time": "2021-01-16 03:09:44 +0000 UTC",
    "terminated_reason": 116,
    "terminated_description": "node was unconfigured"
  }
````
Then the node was unregistered and registered with a policy. Then no nodes have ever returned from the /search api.
I checked that the agreements table was empty for this node.
The node policy `"lastUpdated": "2021-01-16T03:10:10.515Z[UTC]"`
The node  ` "lastUpdated": "2021-01-16T03:10:13.164Z[UTC]"`

**Comment by naphelps** [comment]
Could be related to issue #437

**Comment by sf2ne** [comment]
Verified fixformatting method with testing, bug has not been reproduced
