### ISSUE TITLE
exchange gives inconsistent result when user and node have same id

### ISSUE THREAD

**Issue by linggao** [open-horizon/exchange-api#454]
In a case where user name for the IAM key and node id and org id are the same, the node list command did not give consistent result. But it only happens in one IEAM cluster. 
1. First create the node:  
````
hzn exchange node create -o myname -u <apikey> myname 12345
````
2. Then liste the node:
````
curl https://<mycluster>/edge-exchange/v1/orgs/myname/nodes/myname -u <apikey> -k |jq 
````
Sometimes it returned 200, sometimes it returned 401 with invalid-credentials
3. We got the logs for the 3 exchange pods. We found out, that for the first few minutes, all the 200 returns were from the same exchange pod that created the node. All the 401 returns were from the other 2 pods. The 401 returns look like this:
````
[INFO] [01/25/2021 14:37:54.617] [actors-akka.actor.default-dispatcher-76300] [akka.actor.ActorSystemImpl(actors)] GET http://<mycluster>/v1/orgs/myname/nodes/myname: rejected with: List(Rejection http code: 401 Unauthorized, message: invalid credentials)
````
4. After a few minutes, all the list call to this node returned 401, even with the pod that created this node.
5. The following is what the user, org and node look like: 
````
User:
{
  "myname/myname": {
    "admin": true,
    "email": "contact@myname.com",
    "hubAdmin": false,
    "lastUpdated": "2021-01-21T12:42:45.541Z[UTC]",
    "password": "********",
    "updatedBy": "root/edgeserviceadmin"
  }
}

Org:
{
  "myname": {
    "description": "org for myname",
    "heartbeatIntervals": {
      "intervalAdjustment": 0,
      "maxInterval": 0,
      "minInterval": 0
    },
    "label": "myname",
    "lastUpdated": "2021-01-21T12:42:44.734Z[UTC]",
    "limits": {
      "maxNodes": 0
    },
    "orgType": "",
    "tags": {
      "cloud_id": "b779-0feb"
    }
  }
}

Node:
{
  "myname/myname": {
    "token": "********",
    "name": "myname",
    "owner": "myname/myname",
    "nodeType": "device",
    "pattern": "",
    "registeredServices": [],
    "msgEndPoint": "",
    "softwareVersions": {},
    "lastHeartbeat": "",
    "publicKey": "",
    "arch": "",
    "userInput": [],
    "heartbeatIntervals": {
      "minInterval": 0,
      "maxInterval": 0,
      "intervalAdjustment": 0
    },
    "lastUpdated": "2021-01-25T14:37:30.912Z[UTC]"
  }
}
````

**Comment by linggao** [comment]
For a different test, I created a user  with a different id from the org id.
````
hzn exchange user create -o myname -u <apikey> lingtest 12345 me@me.com
````
Then I created a node with the same user name using the new user as the credential.
````
hzn exchange node create  -o myname -u  lingtest:12345 lingtest 12345
````
Then I list the node using the node credential:
````
hzn exchange node list -o myname -u  lingtest:12345 lingtest
````
Sometime it returned good result, sometimes it returned  
````
{"code":"access-denied","msg":"Access denied: 'myname/lingtest' does not have authorization: READ_ALL_NODES node=myname/lingtest"}
````
But after a minutes, the return results were all good.

**Comment by linggao** [comment]
I only saw the bad result on this particular cluster.  Maybe it has something to do with the cache of the exchange?

**Comment by bmpotter** [comment]
i just did my own testing in my development environment and these are my results:
- if there is a local exchange user with the same id as the node, then the node creds can’t be used successfully
- if there is an IAM user with the same id as the node, then the node creds CAN be used successfully
