### ISSUE TITLE
Avoid DB reads if maxMessagesInMailbox and maxAgreements are 0 which is default and means unlimited

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/exchange-api#455]
In both NodesRoutes.scala and AgbotRoutes.scala when `POST /orgs/{orgid}/agbots/{id}/msgs` or `PUT /orgs/{orgid}/nodes/{id}/agreements/{agid}` is called, the code checks the count of those entities in the DB first and then checks the exchange config parameter which controls the limits which defaults to 0 meaning unlimited. Since our default is 0 and seems unlikely a customer would change those parameters, an optimization would be to check the parameter first and if 0, avoid the call to the DB to get the count.  For 10k nodes, this would avoid > 80k DB reads when agreements are forming

**Comment by bmpotter** [comment]
Implemented in PR https://github.com/open-horizon/exchange-api/pull/461 and docker image `openhorizon/amd64_exchange-api:2.60.0` .
