### ISSUE TITLE
Change config value akka.http.server.request-timeout to 45s

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/exchange-api#456]
Under load, I have found that setting 
```
  "akka": {
          "akka.http.server.request-timeout": "45s"
}
```
in the Exchange config.json file eliminates many of the akka read timeouts. The default is 20 sec. When a timeout occurs, the agent has to retry so reducing the timeouts will reduce load on the exchange & exchangedb.

**Comment by bmpotter** [comment]
Implemented in PR https://github.com/open-horizon/exchange-api/pull/461 and docker image `openhorizon/amd64_exchange-api:2.60.0` .
