### ISSUE TITLE
Altering SQL to avoid inequalities for checking NF for /changes route for nodes reduces ExchangeDB CPU utilization 

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/exchange-api#462]
More details to come...

**Comment by dlarson04** [comment]
Below is the scala code that causes a significant reduction in exchangeDB CPU utilization by avoiding the 
in-equalities in the SQL for the `/changes` route

```
case _: INode =>
 // if its a node calling then it doesn't want information about any other nodes
 qFilter = qFilter.filter(u => (u.orgId === orgId) || u.public === "true").filter(u => (u.category === "node" && u.id === ident.getIdentity) || (u.category === "service" || u.category === "org"))
 ```
I think the only difference for the agent is that it won't receive notifications  when a policy or pattern is changed, but my testing shows that the agbot drives behavior (ie. cancelling or creating agreements) based on these changes

Note, I do see that inequalities are used when the agbot calls the /changes route but I haven't see these show up 
when looking at running SQL queries... I suspect because this only runs 2 times in about 10 seconds compared to
potentially thousands of agents calling the changes route

**Comment by bmpotter** [comment]
Fixed in https://github.com/open-horizon/exchange-api/pull/471 .
