### ISSUE TITLE
Update lastUpdated field for the node table after the service_configstate is updated

### ISSUE THREAD

**Issue by linggao** [open-horizon/exchange-api#476]
After POST  v1/orgs/<org>/nodes/<nodeid>/services_configstate, the service configstate is updated in the registeredResources in the node table. However, the lastUpdated filed is not updated so that /changes API cannot pick up this change. 
Anax issue [2355](https://github.com/open-horizon/anax/issues/2355) depends on it.

**Comment by sf2ne** [comment]
also verified by anax
