### ISSUE TITLE
Failed to create org when the root user is both admin and hubadmin

### ISSUE THREAD

**Issue by linggao** [open-horizon/exchange-api#479]
1. Use `hzn exchange user create` command to create an user in the root org. Set both admin and hubadmin to be true.
2. Use this user to create an org. Got the following error.
````
Error: bad HTTP code 403 from POST https://cp-console.ieam-roks-stg-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-exchange/v1/orgs/anaxsquad3: access-denied, Access denied: 'root/myadmin2' does not have authorization: CREATE_ORGS org=
````

**Comment by sf2ne** [comment]
I think this issue ultimately boils down to, can the exchange's auth structure handle a user having more than one role at the same time? Because from this issue it seems like it. If that's the case, is a user having more than one role something we want the exchange to support?

**Comment by sf2ne** [comment]
This issue can be replicated with a locally running exchange.
Step 1: Create a hubadmin user in the exchange with the `admin` field set to true as well:

**Comment by sf2ne** [comment]
Verified on roks-stg that you cannot create a user in the `root` org who is both a hubadmin and an orgadmin at the same time:
```
curl -v -k -X POST -sS -u "$ROKS_ROOT" "$ROKS_EXCHANGE/orgs/root/users/badhubadminsftest" -H "accept: application/json" -H "Content-Type: application/json" -d @test_user.json | jq

{
  "password": "abc123doremi",
  "admin": true,
  "hubAdmin": true,
  "email": "fakeemail@gmail.com"
}

{
  "code": "invalid-input",
  "msg": "User cannot be admin and hubAdmin at the same time"
}
```
