### ISSUE TITLE
New exchange resource to provide a list of management hub APIs

### ISSUE THREAD

**Issue by dabooz** [open-horizon/exchange-api#492]
Add a new resource, called /hubapis which returns a list of the management hub APIs:

GET /hubapis
Returns HTTP 200:
```
{
  "exchange": "<exchange-url>",
  "mms": "<css-url>",
  "management-console": "<ui-url>",
  "agreement-bot": "<agbot-secure-api-url>"
}
```

**Comment by bmpotter** [comment]
I think @dabooz is going to close this issue, because after reviewing the design it doesn't look like we need this.

**Comment by bmpotter** [comment]
We decided we don't need this API. Putting the URLs in agent-install.cfg in CSS is the alternative that is already being used.
