### ISSUE TITLE
Deployment policy does not support 'secretBinding' for PUT and PATCH

### ISSUE THREAD

**Issue by linggao** [open-horizon/exchange-api#506]
- [ ] Change the pattern and deployment policy request body classes to use the schema shown in issue 505. Both of these use the same [OneSecretBindingService class](https://github.com/open-horizon/exchange-api/blob/b90546494646d231052e297d92120381d352e1b6/src/main/scala/com/horizon/exchangeapi/tables/Patterns.scala#L21), so you just have to change the `secrets` part of that class to be: `secrets: List[Map[String, String]]`  And then delete the `OneSecretBindingValue` class because it is no longer used. Also, change the tests accordingly.
- [ ] `PUT /orgs/{orgid}/business/policies/{policy}` does not give an error, but does not update the `secretBinding` section of the resource either. Debug to figure out why and fix it, and change the automated test to check that it really does update the resource so it would have caught this problem.
- [ ] `PATCH /orgs/{orgid}/business/policies/{policy}` returns 400. Fix it and add a test for it.

**Comment by sf2ne** [comment]
Verified by anax
