### ISSUE TITLE
Add version to the node registeredServices

### ISSUE THREAD

**Issue by linggao** [open-horizon/exchange-api#518]
We have been assuming that there is only one version of the same service running on an agent at a time. Now that agent is supporting multiple versions of the same service,  like the case that one is the dependent service, one is a top level service for a different agreement, we'd like the exchange support the following:
1. add `version` attribute to the `registeredServices` for a node resource because it holds the config state for a service. 
2. add `version` attribute in the request body for POST `orgs/<org>/nodes/<nodeid>/services_configstate`

**Comment by linggao** [comment]
This is what we have today for the `registeredServices`:
```
    "registeredServices": [
      {
        "url": "e2edev@somecomp.com/https://bluehorizon.network/services/weather",
        "properties": [],
        "numAgreements": 0,
        "policy": "",
        "configState": "active"
      },
      {
        "url": "e2edev@somecomp.com/https://bluehorizon.network/services/gpstest",
        "properties": [],
        "numAgreements": 0,
        "policy": "",
        "configState": "active"
      },
```

**Comment by sf2ne** [comment]
Verified by anax
