### ISSUE TITLE
Updates to node management policy resources are not being reported by the changes api

### ISSUE THREAD

**Issue by MaxMcAdam** [open-horizon/exchange-api#555]
Creation, update, and deletion of nmps are not reflected in what the changes api reports.

**Comment by naphelps** [comment]
Admins/Agbots/User are unaffected. Scope is limited to just Nodes.

Nodes are missing a query filter allowing resources of type `mgmtpolicy`. Line 1083.

Before:
`qFilter = qFilter.filter(u => (u.orgId === orgId) || u.public === "true").filter(u => (u.category === "node" && u.id === ident.getIdentity) || (u.category === "service" || u.category === "org"))`

After:
`qFilter = qFilter.filter(u => (u.orgId === orgId) || u.public === "true").filter(u => (u.category === "mgmtpolicy") || (u.category === "node" && u.id === ident.getIdentity) || (u.category === "service" || u.category === "org"))`
