### ISSUE TITLE
UI shows Nodes count as zero in the service card even if more than one node is running that service

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/exchange-api#560]
UI shows Nodes count as zero in the service card even if more than one node is running that service

To Reproduce

    Register a node and deploy a service on nodes using policy.
    Check the service card of the deployed service.
    May need to deploy/undeploy the service

Expected behavior
The number should not be zero when service is deployed. It should show number of nodes running that service.

See  https://github.ibm.com/Edge-Fabric/edge-fabric-mgmt-ui/issues/1752 for additional details

**Comment by naphelps** [comment]
The Exchange is incorrectly applying a node owner filter for Org Admin users.
Current: `if(!ident.isSuperUser || !ident.isAdmin) qFilter = qFilter.filter(_.owner === ident.identityString)`
- Does not apply filter for root user, but does for org admins

Fixed: `if(!(ident.isSuperUser || ident.isAdmin)) qFilter = qFilter.filter(_.owner === ident.identityString)`
- Does not apply filter for both root user and org admins.
