### ISSUE TITLE
Node Groups: Schema Changes

### ISSUE THREAD

**Issue by naphelps** [open-horizon/exchange-api#591]
### Description
Create two new tables.

Reference: https://scala-slick.org/doc/3.3.3/schemas.html

#### Table Name
`node_group`

#### Columns
- `description`: String
- `group`: Long or String - DB sequence (Slick `O.AutoInc`)
- `name`: String
- `organization`: String
- `updated`: java.sql.Timestamp

#### Primary Key
`group`

#### Foreign Keys
`node_group.organization` -> `orgs.orgid`

#### Unique index
(`organization`, `name`)

#### Table Name
`node_group_assignment`

#### Columns
- `group`: Long or String
- `node`: String

#### Primary Key
`node`

#### Foreign Keys
- `node_group_assignment.group` -> `node_group.group`
- `node_group_assignment.node` -> `nodes.id`

### Resource Changes
- Create a new `ResChangeResource` type called `NODEGROUP`
- Create a new `ResChangeCategory` type called `NODEGROUP`

**Comment by lorenzoking** [comment]
@naphelps For the Unique Index
```Unique index
(organization, name)
```
Is the name == description in the table columns?

**Comment by naphelps** [comment]
Sorry, I missed `name` as a column. This table will work similarly to the Nodes table (id = group, name = name).
