### ISSUE TITLE
Return 404 in "GET /orgs/{orgid}/status" when non-existent orgId is supplied

### ISSUE THREAD

**Issue by ewee33** [open-horizon/exchange-api#624]
Currently in the route `GET /orgs/{orgid}/status`, if the caller supplies an `orgId` that doesn't exist in the exchange, this route will succeed with code `200 OK` and return zeroes for all values in the response body. This behavior is unintended.

The intended behavior should be that this route returns a `404 NOT FOUND` code when the supplied `orgId` does not exist in the exchange. This route should be updated with this new behavior, and the associated test suite should be updated as well to test this behavior.

**Comment by naphelps** [comment]
Fixed in v2.126.0.
