### ISSUE TITLE
Change exchange response format of getting a single HA group to match other exchange responses when listing an item

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/exchange-api#643]
Currently, Exchange returns an array element when listing one hagroup.

```
# curl -s -w "%{http_code}" -X GET  -u $HZN_ORG_ID/$HZN_EXCHANGE_USER_AUTH  $HZN_EXCHANGE_URL/orgs/$HZN_ORG_ID/hagroups/edge-aug29-1_HAGroup --insecure | jq '.'
{
  "nodeGroups": [
    {
      "name": "edge-aug29-1_HAGroup",
      "description": "edge-aug29-1_HAGroup",
      "members": [],
      "lastUpdated": "2022-10-14T13:00:14.785550329Z[UTC]"
    }
  ]
}
```

but when listing a node, it does not have an array

```
root@edge-aug29-1:~/edge-automation/qa-automation/ha-groups# curl -s -w "%{http_code}" -X GET  -u $HZN_ORG_ID/$HZN_EXCHANGE_USER_AUTH  $HZN_EXCHANGE_URL/orgs/$HZN_ORG_ID/nodes/edge-postinstall-1 --insecure | jq '.'
{
  "nodes": {
    "dal-org/edge-postinstall-1": {
      "token": "********",
      "name": "edge-postinstall-1",
      "owner": "dal-org/admin",
      "nodeType": "device",
      "pattern": "IBM/pattern-ibm.helloworld",
      "registeredServices": [
        {
```

The HA group response should match the other exchange responses

**Comment by naphelps** [comment]
@dlarson04 Per JSON's spec the HA Groups should use an array of objects, as it is an array of objects. As are the others. It is actually the other routes that are not correct. If memory serves the first developers of the Exchange did not know how to convert a list of objects into a JSON array through the translatation layer, which is how the present day responses came to be. These routes have also already been shipped to the open source community and this request would create non-backward compatible change.

**Comment by johnwalicki** [comment]
Do we know how the current json responses are being consumed?   While I don't like breaking changes, if we can improve it, we most certain can discuss it.

**Comment by dlarson04** [comment]
I would rather be consistent from an hzn CLI perspective. Sure the routes are in open source but I think it is a safe bet that no one is using ha groups yet. In my opinion, we should change it now

**Comment by naphelps** [comment]
In order to complete this request it would require the creation of processes and structures in the Exchange to manually manipulate the out-going data heavy handily. This adds performance bottlenecks, additional code base clutter, additional testing overhead, and technical debt. I would rather start a discussion and plan to improve the older route responses, helping to reduce and eliminate the above issues while moving us in the direction of consistent JSON responses.

**Comment by dlarson04** [comment]
after talking with Nathan and hzn cli team, we will cancel this exchange issue and make the hzn cli command format the response to match the others
@linggao
