### ISSUE TITLE
Documentation: Migrate content from base README to /docs

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/exchange-api#665]
Following the pattern set in the [anax repo README](https://github.com/open-horizon/anax/blob/master/README.md), move the contents to `/docs/README.md` and instead have the contents in the repo root folder cover:

* An introduction to the purpose and contents of the repo, as well as related repos
* Links to relevant documentation on the documentation web site
* Development/contributing instructions
* Information about any deprecated commands or APIs
* How to report security issues

**Comment by joewxboy** [comment]
@naphelps anything in the description for this issue that you'd like to modify or expand on before this issue is assigned to a volunteer?

**Comment by naphelps** [comment]
@joewxboy Nope, assign away!

**Comment by joewxboy** [comment]
@naphelps Please take a look at the new [README.md file](https://github.com/open-horizon/exchange-api) and follow the link in the first paragraph to view [the repo docs on the documentation web site](https://open-horizon.github.io/docs/exchange-api/README/).

Let me know in this issue comments if we need to make any changes.
