### ISSUE TITLE
Feature Request: Create build pipeline to build and publish Exchange-API artifacts

### ISSUE THREAD

**Issue by bencourliss** [open-horizon/exchange-api#677]
Currently the Exchange-API container image is built and published by an IBM-internal Jenkins pipeline that make it difficult for open-source developers to see how its done. In addition, this is only done on a nightly basis with no way for non-IBM employees to trigger it.

We need to have a pipeline that builds and publishes the Exchange-API container image into Dockerhub. This pipeline should ideally take the form of Github Actions and operate off of pull requests. The pipeline should publish the testing tag to Dockerhub upon completion.

**Comment by dcmartin** [comment]
There is some support for open source projects to utilize GH resources to build such artefacts; IDK about Linux Foundation or others who may also provide.

**Comment by bencourliss** [comment]
Yes, we will be implementing this with Github Actions. I've assigned this to @blakep7 who is an intern working for IBM this summer and has been cranking away at it and should have a PR soon.
