### ISSUE TITLE
Build failure caused by slick v. 3.2.0-RC1 (released 2/10)

### ISSUE THREAD

**Issue by michaeldye** [open-horizon/exchange-api#8]
A build on 2/11 pulled slick v 3.2.0-RC1 (published 2/10) which breaks db connection pool setup.

Deps:

<pre>
[info] com.horizon:exchange-api_2.11:0.1.0 [S]
[info]   +-ch.qos.logback:logback-classic:1.2.1
[info]   | +-ch.qos.logback:logback-core:1.2.1
[info]   | +-org.slf4j:slf4j-api:1.7.22
[info]   | 
[info]   +-com.mchange:c3p0:0.9.5.2
[info]   | +-com.mchange:mchange-commons-java:0.2.11
[info]   | 
[info]   +-com.pauldijou:jwt-core_2.11:0.10.0 [S]
[info]   | +-com.pauldijou:jwt-core-impl_2.11:0.10.0 [S]
[info]   | +-org.bouncycastle:bcpkix-jdk15on:1.52
[info]   |   +-org.bouncycastle:bcprov-jdk15on:1.52
[info]   |   
[info]   +-com.sun.mail:javax.mail:1.5.6
[info]   | +-javax.activation:activation:1.1
[info]   | 
[info]   +-com.typesafe.slick:slick-hikaricp_2.11:3.2.0-RC1 [S]
[info]   | +-com.typesafe.slick:slick_2.11:3.2.0-RC1 [S]
[info]   | | +-com.typesafe:config:1.2.1 (evicted by: 1.3.1)
[info]   | | +-com.typesafe:config:1.3.1
[info]   | | +-org.reactivestreams:reactive-streams:1.0.0
[info]   | | +-org.slf4j:slf4j-api:1.7.18 (evicted by: 1.7.22)
[info]   | | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   | | +-org.slf4j:slf4j-api:1.7.22
[info]   | | 
[info]   | +-com.zaxxer:HikariCP:2.5.1 (evicted by: 2.6.0)
[info]   | | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   | | +-org.slf4j:slf4j-api:1.7.22
[info]   | | 
[info]   | +-com.zaxxer:HikariCP:2.6.0
[info]   |   +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   |   +-org.slf4j:slf4j-api:1.7.22
[info]   |   
[info]   +-com.typesafe.slick:slick_2.11:3.2.0-M2 [S] (evicted by: 3.2.0-RC1)
[info]   | +-com.typesafe:config:1.2.1 (evicted by: 1.3.1)
[info]   | +-com.typesafe:config:1.3.1
[info]   | +-org.reactivestreams:reactive-streams:1.0.0
[info]   | +-org.slf4j:slf4j-api:1.7.18 (evicted by: 1.7.22)
[info]   | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   | +-org.slf4j:slf4j-api:1.7.22
[info]   | 
[info]   +-com.typesafe.slick:slick_2.11:3.2.0-RC1 [S]
[info]   | +-com.typesafe:config:1.2.1 (evicted by: 1.3.1)
[info]   | +-com.typesafe:config:1.3.1
[info]   | +-org.reactivestreams:reactive-streams:1.0.0
[info]   | +-org.slf4j:slf4j-api:1.7.18 (evicted by: 1.7.22)
[info]   | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   | +-org.slf4j:slf4j-api:1.7.22
[info]   | 
[info]   +-com.typesafe:config:1.3.1
[info]   +-com.zaxxer:HikariCP:2.6.0
[info]   | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   | +-org.slf4j:slf4j-api:1.7.22
[info]   | 
[info]   +-javax.mail:javax.mail-api:1.5.6
[info]   +-org.json4s:json4s-jackson_2.11:3.5.0 [S]
[info]   | +-com.fasterxml.jackson.core:jackson-databind:2.8.4
[info]   | | +-com.fasterxml.jackson.core:jackson-annotations:2.8.0
[info]   | | +-com.fasterxml.jackson.core:jackson-core:2.8.4
[info]   | | 
[info]   | +-org.json4s:json4s-core_2.11:3.5.0 [S]
[info]   |   +-com.thoughtworks.paranamer:paranamer:2.8
[info]   |   +-org.json4s:json4s-ast_2.11:3.5.0 [S]
[info]   |   +-org.json4s:json4s-scalap_2.11:3.5.0 [S]
[info]   |   +-org.scala-lang.modules:scala-xml_2.11:1.0.6 [S]
[info]   |   
[info]   +-org.json4s:json4s-native_2.11:3.5.0 [S]
[info]   | +-org.json4s:json4s-core_2.11:3.5.0 [S]
[info]   |   +-com.thoughtworks.paranamer:paranamer:2.8
[info]   |   +-org.json4s:json4s-ast_2.11:3.5.0 [S]
[info]   |   +-org.json4s:json4s-scalap_2.11:3.5.0 [S]
[info]   |   +-org.scala-lang.modules:scala-xml_2.11:1.0.6 [S]
[info]   |   
[info]   +-org.mindrot:jbcrypt:0.3m
[info]   +-org.postgresql:postgresql:9.4.1212
[info]   +-org.scalaj:scalaj-http_2.11:2.3.0 [S]
[info]   +-org.scalatra:scalatra-auth_2.11:2.5.0 [S]
[info]   | +-org.scalatra:scalatra_2.11:2.5.0 [S]
[info]   |   +-com.googlecode.juniversalchardet:juniversalchardet:1.0.3
[info]   |   +-eu.medsea.mimeutil:mime-util:2.1.3
[info]   |   | +-org.slf4j:slf4j-api:1.5.6 (evicted by: 1.7.22)
[info]   |   | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   |   | +-org.slf4j:slf4j-api:1.7.22
[info]   |   | 
[info]   |   +-org.apache.commons:commons-lang3:3.5
[info]   |   +-org.clapper:grizzled-slf4j_2.11:1.3.0 [S]
[info]   |   | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   |   | +-org.slf4j:slf4j-api:1.7.22
[info]   |   | +-org.slf4j:slf4j-api:1.7.7 (evicted by: 1.7.22)
[info]   |   | 
[info]   |   +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.4 [S]
[info]   |   +-org.scala-lang.modules:scala-xml_2.11:1.0.6 [S]
[info]   |   +-org.scalatra:scalatra-common_2.11:2.5.0 [S]
[info]   |   +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   |   +-org.slf4j:slf4j-api:1.7.22
[info]   |   
[info]   +-org.scalatra:scalatra-json_2.11:2.5.0 [S]
[info]   | +-org.json4s:json4s-core_2.11:3.5.0 [S]
[info]   | | +-com.thoughtworks.paranamer:paranamer:2.8
[info]   | | +-org.json4s:json4s-ast_2.11:3.5.0 [S]
[info]   | | +-org.json4s:json4s-scalap_2.11:3.5.0 [S]
[info]   | | +-org.scala-lang.modules:scala-xml_2.11:1.0.6 [S]
[info]   | | 
[info]   | +-org.scalatra:scalatra_2.11:2.5.0 [S]
[info]   |   +-com.googlecode.juniversalchardet:juniversalchardet:1.0.3
[info]   |   +-eu.medsea.mimeutil:mime-util:2.1.3
[info]   |   | +-org.slf4j:slf4j-api:1.5.6 (evicted by: 1.7.22)
[info]   |   | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   |   | +-org.slf4j:slf4j-api:1.7.22
[info]   |   | 
[info]   |   +-org.apache.commons:commons-lang3:3.5
[info]   |   +-org.clapper:grizzled-slf4j_2.11:1.3.0 [S]
[info]   |   | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   |   | +-org.slf4j:slf4j-api:1.7.22
[info]   |   | +-org.slf4j:slf4j-api:1.7.7 (evicted by: 1.7.22)
[info]   |   | 
[info]   |   +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.4 [S]
[info]   |   +-org.scala-lang.modules:scala-xml_2.11:1.0.6 [S]
[info]   |   +-org.scalatra:scalatra-common_2.11:2.5.0 [S]
[info]   |   +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   |   +-org.slf4j:slf4j-api:1.7.22
[info]   |   
[info]   +-org.scalatra:scalatra-swagger_2.11:2.5.0 [S]
[info]   | +-org.json4s:json4s-ext_2.11:3.5.0 [S]
[info]   | | +-joda-time:joda-time:2.9.5
[info]   | | +-org.joda:joda-convert:1.8.1
[info]   | | 
[info]   | +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.4 [S]
[info]   | +-org.scalatra:scalatra-json_2.11:2.5.0 [S]
[info]   | | +-org.json4s:json4s-core_2.11:3.5.0 [S]
[info]   | | | +-com.thoughtworks.paranamer:paranamer:2.8
[info]   | | | +-org.json4s:json4s-ast_2.11:3.5.0 [S]
[info]   | | | +-org.json4s:json4s-scalap_2.11:3.5.0 [S]
[info]   | | | +-org.scala-lang.modules:scala-xml_2.11:1.0.6 [S]
[info]   | | | 
[info]   | | +-org.scalatra:scalatra_2.11:2.5.0 [S]
[info]   | |   +-com.googlecode.juniversalchardet:juniversalchardet:1.0.3
[info]   | |   +-eu.medsea.mimeutil:mime-util:2.1.3
[info]   | |   | +-org.slf4j:slf4j-api:1.5.6 (evicted by: 1.7.22)
[info]   | |   | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   | |   | +-org.slf4j:slf4j-api:1.7.22
[info]   | |   | 
[info]   | |   +-org.apache.commons:commons-lang3:3.5
[info]   | |   +-org.clapper:grizzled-slf4j_2.11:1.3.0 [S]
[info]   | |   | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   | |   | +-org.slf4j:slf4j-api:1.7.22
[info]   | |   | +-org.slf4j:slf4j-api:1.7.7 (evicted by: 1.7.22)
[info]   | |   | 
[info]   | |   +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.4 [S]
[info]   | |   +-org.scala-lang.modules:scala-xml_2.11:1.0.6 [S]
[info]   | |   +-org.scalatra:scalatra-common_2.11:2.5.0 [S]
[info]   | |   +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   | |   +-org.slf4j:slf4j-api:1.7.22
[info]   | |   
[info]   | +-org.scalatra:scalatra_2.11:2.5.0 [S]
[info]   |   +-com.googlecode.juniversalchardet:juniversalchardet:1.0.3
[info]   |   +-eu.medsea.mimeutil:mime-util:2.1.3
[info]   |   | +-org.slf4j:slf4j-api:1.5.6 (evicted by: 1.7.22)
[info]   |   | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   |   | +-org.slf4j:slf4j-api:1.7.22
[info]   |   | 
[info]   |   +-org.apache.commons:commons-lang3:3.5
[info]   |   +-org.clapper:grizzled-slf4j_2.11:1.3.0 [S]
[info]   |   | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   |   | +-org.slf4j:slf4j-api:1.7.22
[info]   |   | +-org.slf4j:slf4j-api:1.7.7 (evicted by: 1.7.22)
[info]   |   | 
[info]   |   +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.4 [S]
[info]   |   +-org.scala-lang.modules:scala-xml_2.11:1.0.6 [S]
[info]   |   +-org.scalatra:scalatra-common_2.11:2.5.0 [S]
[info]   |   +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   |   +-org.slf4j:slf4j-api:1.7.22
[info]   |   
[info]   +-org.scalatra:scalatra_2.11:2.5.0 [S]
[info]   | +-com.googlecode.juniversalchardet:juniversalchardet:1.0.3
[info]   | +-eu.medsea.mimeutil:mime-util:2.1.3
[info]   | | +-org.slf4j:slf4j-api:1.5.6 (evicted by: 1.7.22)
[info]   | | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   | | +-org.slf4j:slf4j-api:1.7.22
[info]   | | 
[info]   | +-org.apache.commons:commons-lang3:3.5
[info]   | +-org.clapper:grizzled-slf4j_2.11:1.3.0 [S]
[info]   | | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   | | +-org.slf4j:slf4j-api:1.7.22
[info]   | | +-org.slf4j:slf4j-api:1.7.7 (evicted by: 1.7.22)
[info]   | | 
[info]   | +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.4 [S]
[info]   | +-org.scala-lang.modules:scala-xml_2.11:1.0.6 [S]
[info]   | +-org.scalatra:scalatra-common_2.11:2.5.0 [S]
[info]   | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.22)
[info]   | +-org.slf4j:slf4j-api:1.7.22
[info]   | 
[info]   +-org.slf4j:slf4j-api:1.7.22
</pre>

Pinning Slick deps to 3.2.0-M2 built for me. It'd be best if all dependencies were controlled to ensure repeatable, predictable builds.

**Comment by bmpotter** [comment]
I found this problem on friday and fixed it over the weekend. Just merged the PR now.

I understand the value of predictable builds, but there are 25 dependencies, each with their own version, and i would never be able to specify the correct version of every one of them to work together properly, and maintain that going forward.

Was this build done by launchpad?
